patchedDependencies:
    app-builder-lib@26.15.3: patches/app-builder-lib@26.15.3.patch
    arrpc@3.5.0: patches/arrpc@3.5.0.patch
    electron-updater: patches/electron-updater.patch
nodeLinker: hoisted
allowBuilds:
    "@vencord/venmic": true
    electron: true
    electron-winstaller: false
    esbuild: true
pmOnFail: warn
verifyDepsBeforeRun: warn
recursiveInstall: false
packages:
    - packages/*
overrides:
    "@noble/hashes": "1.4.0"
minimumReleaseAgeExclude:
    - electron
